add dry_run mode, support deleting group registered runners
containeroo/cleanup-gitlab-runner pull request #22
Opened 2022-07-26 19:40 UTC by itsmethemojo

i added following features to support my usescases
 
 * dry run mode (DRY_RUN)
 * optional basic auth credentials
 * optional giving in a group id to delete runners registered on the specific group (thats interesting if you own a group but not the gitlab)

2022-07-26 21:53 UTC, gi8lino requested changes
hi @itsmethemojo 
I don't like `else` 🙈
rest is great👍

2022-07-26 21:53 UTC, gi8lino commented on cleanup_gitlab_runner.py
> +            else:
```suggestion
                continue
```

2022-07-26 21:53 UTC, gi8lino commented on cleanup_gitlab_runner.py
> +                runner.delete()
```suggestion
            runner.delete()
```

2022-07-26 22:54 UTC, itsmethemojo commented
should i manually squash or will this anyway be done with the PR?

2022-07-27 06:43 UTC, merged

2022-07-27 06:43 UTC, gi8lino commented
Hi @itsmethemojo 
Thank you very much for your contribution!